### ISSUE TITLE
取得できない曲がある

### ISSUE THREAD

**Issue by leaysgur** [leader22/mmss-client#2]
https://music.lealog.net/api/track?path=%E5%AE%89%E8%97%A4%E8%A3%95%E5%AD%90%2F%E5%A4%A7%E4%BA%BA%E3%81%AE%E3%81%BE%E3%81%97%E3%82%99%E3%82%81%E3%81%AA%E3%82%AB%E3%83%8F%E3%82%99%E3%83%BC%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%B9%E3%82%99%2F%E5%AE%89%E8%97%A4%E8%A3%95%E5%AD%90%20-%20%E5%90%9B%E3%81%AF1000%25.mp3

```
URIError: URI malformed
   at decodeURIComponent (native)
   at router.get.err (/var/www/music/mmss-server/lib/server/routes/authorized.js:12:32)
   at Layer.handle [as handle_request] (/var/www/music/mmss-server/node_modules/express/lib/router/layer.js:95:5)
   at next (/var/www/music/mmss-server/node_modules/express/lib/router/route.js:131:13)
   at _isLogin (/var/www/music/mmss-server/lib/server/routes/authorized.js:30:12)
   at Layer.handle [as handle_request] (/var/www/music/mmss-server/node_modules/express/lib/router/layer.js:95:5)
   at next (/var/www/music/mmss-server/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/var/www/music/mmss-server/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/var/www/music/mmss-server/node_modules/express/lib/router/layer.js:95:5)
   at /var/www/music/mmss-server/node_modules/express/lib/router/index.js:277:22
```

**Comment by leaysgur** [comment]
fix https://github.com/leader22/mmss-server/commit/12d79b836f49f43a5531f9a150e17855b0e10631
